name: tabbed_sliverlist
description: A simple flutter plugin to setup sliverlist with TabBar with minimal code.
version: 0.1.0
homepage: https://github.com/akshay512/tabbed_sliverlist

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
